name: Build & push image to ECR

on:
  push:
    branches: ["Experiment"]

jobs:
  Build-push-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push docker images
        id: build-the-image
        env:
          ECR_REGISTRY: 985182088924.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: hjsat
          IMAGE_TAG: postgres_1989
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:postgress_$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:postgress_$IMAGE_TAG

      - name: Create and switch to branch-test
        run: |
          git checkout -b branch-test origin/branch-test || git checkout branch-test

      - name: Merge changes from branch-Experiment
        run: |
          git merge --no-ff origin/branch-Experiment

      - name: Push changes to branch-test
        run: |
          git push origin branch-test             
