name: Merge Development into Testing

on:
  pull_request:
    types: [closed]

jobs:
  merge-development-into-testing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge Development into Testing
        run: |
          git fetch origin development
          git checkout testing
          git merge --no-ff --no-edit development
          git push origin testing
